#!/usr/bin/env php
<?php
use Zodream\Service\Console;

define('DEBUG', true);                  //是否开启测试模式
define('APP_DIR', __DIR__);            //定义路径
require_once APP_DIR.'/vendor/autoload.php';

config()->set('modules', [
        'default' => 'Zodream\Module\Attack',
]);
$app = new Console(APP_DIR);
$app->autoResponse();